### PR TITLE
Ux 994 update card style and fix  conflicts

### PR DESCRIPTION
**Pull request by pierreOSI**
- Fix the button/grid/card header styling conflicts.
- Apply new visual style to cards (CSS ONLY, approved by design): https://osi-cwds.atlassian.net/browse/CASE-994
- Fix profile picture issue: https://osi-cwds.atlassian.net/browse/INT-622

### CODE REVIEW

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by SashaKyz** [comment]
Build triggered. sha1 is merged.

**Comment by SashaKyz** [comment]
Build started sha1 is merged.

**Comment by SashaKyz** [comment]
Green is good.

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Pull request merged**
