### PR TITLE
Include font-awesome.min.css in distribution to avoid external calls

### PR DESCRIPTION
**Pull request by kelfink**
FIT-558 external font-awesome css reference issue

### CODE REVIEW

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by eckdanny-osi** [comment]
Also consider why import `font-awesome` at all?

**Pull request merged**
