### PR TITLE
Inline storybook documentation

### PR DESCRIPTION
**Pull request by edgibbs**
This change should inline all the docs that exist with the exception of
a few sidenav components where the button remains because of layout issues.

### CODE REVIEW

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!
 No test results found.

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!
 No test results found.

**Comment by snehanagole-osi** [comment]
@edgibbs : What is 'No test results found'. Does it mean 'No failing tests'?

**Comment by edgibbs** [comment]
So the no tests results found is because code coverage isn't setup yet on react-wood-duck.

**Comment by snehanagole-osi** [comment]
@edgibbs : Basic NavLink with inline documentation is looking good. Can we follow the same format for other variations of NavLink. (A gray line separating the NavLink view & documentation).

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!
 No test results found.

**Pull request merged**
