### PR TITLE
More jenkins testing

### PR DESCRIPTION
**Pull request by edgibbs**

### CODE REVIEW

**Comment by SashaKyz** [comment]
Build triggered. sha1 is merged.

**Comment by SashaKyz** [comment]
Build started sha1 is merged.

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by SashaKyz** [comment]
Green is good.

**Comment by edgibbs** [comment]
retest this please

**Comment by SashaKyz** [comment]
Build triggered. sha1 is merged.

**Comment by SashaKyz** [comment]
Build started sha1 is merged.

**Comment by SashaKyz** [comment]
Green is good.

**Comment by edgibbs** [comment]
retest this please

**Comment by SashaKyz** [comment]
Build triggered. sha1 is merged.

**Comment by SashaKyz** [comment]
Build started sha1 is merged.

**Comment by SashaKyz** [comment]
Green is good.

**Comment by edgibbs** [comment]
retest this please

**Pull request closed without merging**
