### PR TITLE
Remove semicolons

### PR DESCRIPTION
**Pull request by saraOSI**
In order to make code more readable by humans, and to be in line with the lint settings for the majority of the projects at CWDS, do not require semicolons in javascript code.

### CODE REVIEW

**Comment by ratneshraval** [comment]
I vote for the semi colons gone.

**Comment by eckdanny-osi** [comment]
I **WANT** semi-colons.

ASI has some whacky behavior. ASI grammar is frequently identified as a issue topic in [tc39 proposals](https://github.com/tc39).

There's good reason IMO that prettier _did not_ target support for it in the beginning and the `--no-semi` option is defaults to adding them.

 > What I recommend is to use semi-colons so you don't have this problem in the first place :)
 > [\@vjeux](https://github.com/prettier/prettier/issues/2662#issuecomment-324818097), -creator of prettier

**Comment by saraOSI** [comment]
@eckdanny-osi Prettier makes some attempts to guard against ASI issues:
> false - Only add semicolons at the beginning of lines that may introduce ASI failures.
(from https://prettier.io/docs/en/options.html#semicolons)

**Comment by edgibbs** [comment]
I don't have strong opinions.  Here are my thoughts:

- I hate semicolons. (OK, that may be a strong opinion)
- Crawford made a rule about always adding semicolons.
- I have had a few bugs in the past caused by missing semicolons.
- Prettier defaults to always adding semicolons, and Prettier is pretty opinionated.
- Prettier lets me mostly leave off semicolons which get added when I save in vim or worst case when I lint.

**Comment by saraOSI** [comment]
@edgibbs I think the main issue we're facing on the non-semicolon side of the house is our particular editors are configured to _remove_ semicolons from lines. Also, as we move code into Wood Duck, we have to change the linting. Maybe I'm fighting the wrong issue here, and we should choose a lint style to be standard across the project. That would be useful, especially as we work toward smaller teams that can be deployed into any one of the code bases. Prettier is one option. CALS is using https://standardjs.com/, and importing a lint configuration that conforms to that standard. Intake has configured our own rules; not sure if those conform to Standard JS or not.

When we didn't have Wood Duck, it was ok that we were also using different lint strategies. As we share more code, I think it increasingly makes sense to share other configurations as well.

As for bugs, prettier claims that it checks for issues that would be caused by the automatic semicolon insertion. Other lint configurations tackle the issue by not allowing lines that start with certain characters, again to fight the few edge cases in which ASI would fail.

**Comment by edgibbs** [comment]
Only Bruno and I made it to the dev leads meeting this week, so we'll try to get a consensus at the next meeting on the direction.

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by SashaKyz** [comment]
Build triggered. sha1 is original commit.

**Comment by SashaKyz** [comment]
Build started sha1 is original commit.

**Comment by SashaKyz** [comment]
Green is good.

**Pull request closed without merging**
